server:
  port: 8085
spring:
  application:
    name: Assisment
  datasource:
    url: jdbc:mysql://localhost:3306/test_test
    username: root
    password: arjun
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
